# This is the *workspace* Cargo.toml
[workspace]
# Lists all packages (crates) in the workspace
members = [
    "engine-core", # Our library (WASM + Rust)
    "cli-demo",    # Our executable (CLI)
]

# You can define default build profiles here
[profile.release]
lto = true